# Generated by Django 3.2.2 on 2021-05-11 08:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Зарегистрирован')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Юзернейм')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('telegram_chat_id', models.PositiveIntegerField(db_index=True, verbose_name='Telegram chat ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Загружен')),
                ('image', models.ImageField(upload_to='receipts', verbose_name='Фото чека')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='draw_app.customer', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FnsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_request_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время первого запроса')),
                ('last_request_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего запроса')),
                ('qr_recognized', models.CharField(db_index=True, max_length=128, verbose_name='Распознанный qr')),
                ('status', models.PositiveSmallIntegerField(choices=[[1, 'Запрос отправлен'], [2, 'Ответ получен'], [3, 'Ответа еще нет'], [4, 'Истек срок']], db_index=True, default=1, verbose_name='Статус')),
                ('answer', models.JSONField(blank=True, db_index=True, default=dict, verbose_name='Ответ налоговой')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fns_orders', to='draw_app.receipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'Запрос к ФНС',
                'verbose_name_plural': 'Запросы к ФНС',
                'ordering': ['-last_request_at'],
            },
        ),
    ]
