# Generated by Django 3.2.2 on 2021-05-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptrecognitionouterrequeststat',
            name='sent_notification',
            field=models.BooleanField(default=False),
        ),
    ]
