# Generated by Django 3.2.2 on 2021-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnsorder',
            name='status',
            field=models.CharField(choices=[('raw', 'не обработан'), ('sent', 'отправлен'), ('received', 'получен'), ('closed', 'закрыт')], db_index=True, default='raw', max_length=25, verbose_name='Статус'),
        ),
    ]
