# Generated by Django 3.2.2 on 2021-05-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcoderecognitionattempt',
            name='recognition_quality_setting',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Настройка качества распознования qr-кодов'),
        ),
        migrations.AlterField(
            model_name='qrcoderecognitionattempt',
            name='reason_for_failure',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Причина неудачи анализа чека'),
        ),
    ]
