# Generated by Django 3.2.2 on 2021-05-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0002_auto_20210521_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptRecognitionOuterRequestStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_to', models.CharField(choices=[('dynamsoft', 'чтение qr-кодов'), ('fns_api', 'получение данных из ФНС')], db_index=True, max_length=25, verbose_name='Наименование сервиса для анализа чека')),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки чека для анализа')),
                ('end_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время получения ответа')),
                ('reason_for_failure', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Причина неудачи анализа чека')),
                ('dynamsoft_quality_setting', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Настройка качества распознования qr-кодов')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='draw_app.receipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'Статистика распознования (qr коды и ФНС)',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_setting',
            field=models.CharField(choices=[('Best Coverage Settings', 'Высокое качество распознавания'), ('Best Speed Settings', 'Высокая скорость распознавания'), ('Balance Settings', 'Сбалансированные настройки'), ('Ultimate Coverage Settings', 'Максимальное качество распознавания')], db_index=True, default='Ultimate Coverage Settings', max_length=30, verbose_name='Варианты настроек распознования баркодов'),
        ),
        migrations.DeleteModel(
            name='QRCodeRecognitionAttempt',
        ),
    ]
