# Generated by Django 3.2.2 on 2021-05-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0002_receiptrecognitionouterrequeststat_sent_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tg_first_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя в Telegram'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tg_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Юзернейм в Telegram'),
        ),
        migrations.AlterField(
            model_name='fnsorder',
            name='check_ticket_info',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Распознанный qr'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='qr_recognized',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Распознанный qr'),
        ),
        migrations.AlterField(
            model_name='receiptrecognitionouterrequeststat',
            name='request_to',
            field=models.CharField(choices=[('dynamsoft', 'чтение qr-кодов'), ('fns_api', 'получение данных из ФНС')], db_index=True, max_length=25, verbose_name='Сервис для анализа чека'),
        ),
        migrations.AlterField(
            model_name='receiptrecognitionouterrequeststat',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки чека'),
        ),
    ]
