# Generated by Django 3.2.2 on 2021-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0005_auto_20210529_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptrecognitionouterrequeststat',
            name='sent_notification',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
