# Generated by Django 3.2.2 on 2021-05-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0006_alter_receiptrecognitionouterrequeststat_sent_notification'),
        ('draw_app', '0006_rename_check_ticket_info_fnsorder_qr_recognized'),
    ]

    operations = [
    ]
