# Generated by Django 3.2.2 on 2021-06-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0007_merge_20210601_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fnsorder',
            name='qr_recognized',
        ),
        migrations.AddField(
            model_name='fnsorder',
            name='message_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID запроса'),
        ),
        migrations.AlterField(
            model_name='fnsorder',
            name='answer',
            field=models.JSONField(default=dict, verbose_name='Ответ налоговой'),
        ),
    ]
