version: '3'
services:
  postgres:
    image: "postgres:12.0-alpine"
    volumes:
      - "../volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-Sunrise23}
      POSTGRES_USER: ${POSTGRES_USER-lucky_draws}
      POSTGRES_DB: ${POSTGRES_USER-lucky_draws}
    restart: always

  node-red:
    image: nodered/node-red
    volumes:
      - "../volumes/node_red:/data"
    ports:
      - "1880:1880"
    environment:
      TZ: Europe/Moscow
      TG_TOKEN: ${TG_TOKEN}
      TG_BOT_NAME: ${TG_BOT_NAME}
    restart: always

  django-rq:
    image: redis
    volumes:
      - "../volumes/redis:/data"
    ports:
      - "6379:6379"
    restart: always
